export const Selectors = {
    title: 'h2#product_title',
    brand: 'div.brand',
    categories: '.current-category > a',
    description: 'div.proddet > p',
    skus_items: 'div.skus-area > div > div',
    skus_item_title: 'div.prod-nome',
    skus_item_price: 'div.prod-pnow',
    skus_item_old_price: 'div.prod-pold',
    skus_content: 'div.card-container',
    skus_image: 'img',
    properties_table_rows: 'table:first > tbody > tr',
    additional_properties_table_rows: 'div#propadd > pure-table pure-table-bordered > tbody > tr',
    review_average_score: 'div#comments > h4',
    comment_section: 'div#comments > div.analisebox',
    commenter_name: 'div.pure-u-21-24 > span.analiseusername',
    commentator_comment_date: 'div.pure-u-21-24 > span.analisedate',
    commentator_given_stars: 'span.analisestars',
    commentator_comment_text: 'p',
}
